// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGjp4C8faSEYpm8sjOh3NaEZKA_dBbK_E',
    appId: '1:526262475794:web:6c2118fe0793a2f47e0ccb',
    messagingSenderId: '526262475794',
    projectId: 'mental-health-app-ec9fc',
    authDomain: 'mental-health-app-ec9fc.firebaseapp.com',
    storageBucket: 'mental-health-app-ec9fc.appspot.com',
    measurementId: 'G-9MCGN2MFN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKEv4Y1c4IbEZbpNRfSzoNSXW0JAWK5g',
    appId: '1:526262475794:android:3e9d86ff033d2fe27e0ccb',
    messagingSenderId: '526262475794',
    projectId: 'mental-health-app-ec9fc',
    storageBucket: 'mental-health-app-ec9fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfi9Ei9mKZq4W3RZ_Z5riJRYsh1vlNj4',
    appId: '1:526262475794:ios:9b503e7afe9789967e0ccb',
    messagingSenderId: '526262475794',
    projectId: 'mental-health-app-ec9fc',
    storageBucket: 'mental-health-app-ec9fc.appspot.com',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfi9Ei9mKZq4W3RZ_Z5riJRYsh1vlNj4',
    appId: '1:526262475794:ios:d982aa41fbc289a07e0ccb',
    messagingSenderId: '526262475794',
    projectId: 'mental-health-app-ec9fc',
    storageBucket: 'mental-health-app-ec9fc.appspot.com',
    iosBundleId: 'com.example.mentalHealthApp.RunnerTests',
  );
}
